// <auto-generated>
// Rewired Constants
// This list was generated on 13-12-2019 15:19:06
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Spirit
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Horizontal Movement")]
        public const int Horizontal = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Vertical Movement")]
        public const int Vertical = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Basic Attack")]
        public const int Attack = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Grab")]
        public const int Grab = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Dash")]
        public const int Dash = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Spirit", friendlyName = "Pause Game")]
        public const int Pause = 6;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int Alt = 1;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
